package week8.day1;

public class LearnExceptionHandling {

	
	public static void main(String[] args) {
		int x =36;
		int y=3,z=0;
		
		try {
			z = x/y;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			
		System.out.println(e);
					}
		
		System.out.println("X divided by Y"+"\t"+z);
				
		;
		
		
			
	}
}
